version: "3"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=letmein
      - MYSQL_DATABASE=emapp
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - dbdata:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080
  backend:
    build:
      context: ./em-app        
    ports:
      - "8080:8080"
    expose:
      - 8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/emapp?autoReconnect=true&useSSL=false
    depends_on:
      - db
  frontend:
    build: 
      context: ./em-app-front
    ports:
      - "4200:4200"
    expose:
      - 4200

volumes:
  dbdata: